# Generated by Django 5.2.4 on 2025-07-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('FAILED', 'failed'), ('REFUNDED', 'refunded')], default='PENDING', max_length=20),
        ),
    ]
